import Navbar from "../components/Navbar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "../components/Footer";
import BackToTop from "../components/BackToTop";
import BackgroundEffects from "../components/BackgroundEffects";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Fixed behind everything — zIndex 0 */}
        <BackgroundEffects />
        {/* All page content sits above the background — zIndex 1 */}
        <div className="relative" style={{ zIndex: 1 }}>
          <Navbar />
          {children}
          <Footer />
          <BackToTop />
        </div>
      </body>
    </html>
  );
}
